// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqbzaolxfimmqmcamxck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxYnphb2x4ZmltbXFtY2FteGNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NjcyMDMsImV4cCI6MjA2ODQ0MzIwM30.eU4fElmLxRAyFXpGf9NhxvHs2jI02szypK3muWf6dS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});